### ISSUE TITLE
Campaign flow

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPAR#10]
This thread is intended to discuss and agree on the flow of the campaign (when things are done: brief, signups, BDA reports, taskings etc).

- For simplicity I suggest we will name each day by a : D+1 (for the first day of the operation).
- I suggest we have one ATO per day (so in principle 1 event per day. But if there is need for a follow up on a mission, then the next even/events can just follow on from the previous one). So a ATO day and a D+ day will mean the same. 
- Tankers / AWACS and other support assets will be in the same place for the entire ATO day. So if a follow on mission takes place within the same day, then we dont do anything with AWACS or tankers or any other supporting assets, and the same airspace restrictions will be in effect.  (of course these are just guidelines and we can adapt if we see a need to do so)
- I suggest we aim for a 2 week cycle (so a combat event every 2 weeks). This should make it fairly doable, if we take turns hosting. Also, it adds some space for Evos campaign and some advanced trainings.

So for a 14 day cycle I would suggest something like this:
- Day 1: Event (Sunday)
- Day 2: AARs and BDAs to be provided (Monday)
- Day 3-8: VIS production and publish new report NLT Day 8 (Monday)
- Day 8-12: CJTF HQ guidace to AOC (priorities/special targets/high value targets, etc)  (supported by VIS)
- Day 12: AOC work day: Taskings/briefing/assignments (Friday)
- Day 13+14: Pilots planning days
- Day 14: Event (Sunday)

**Comment by 132ndNeck** [comment]
- [ ] Test
- [ ] Test 2

**Comment by IAFAssafB** [comment]
Looks good!
I'm thinking if perhaps we should try and represent the GAMETIME in addition to events order. What I mean is to give an indication and sense about "how long" some events in a war could take.
Example for two following events:
OPERATION ACTIVE RESOLVE no.13, D+16
OPERATION ACTIVE RESOLVE no.14, D+19
(Means two events spaced by two weeks (as per your suggestion) , but in gametime occurring 3 days apart to simulate movement of forces for regrouping, setting up for offensives etc. This would give more "material" to think about for the VIS officers when evaluating COAs and prioritizing targets to the CJTF HQ.

As to the timeline between events:
1) It is good to have the deadlines you specified for BDA reporting. Sometimes pilot drag it for some time but once a time frame is in place then they either submit it on time or their BDA will not be taken in to account by the VIS officers and the team would have to deal with the consequences :-) 
2) In the "CJTF HQ guidance to AOC" phase, we should stress that we need primary as well as secondary/contingency missions so that it's easier for us to account for late signoffs / late signups.

**Comment by 132ndNeck** [comment]
> 
>     1. It is good to have the deadlines you specified for BDA reporting. Sometimes pilot drag it for some time but once a time frame is in place then they either submit it on time or their BDA will not be taken in to account by the VIS officers and the team would have to deal with the consequences :-)

Yes, hopefully we can help dicipline people to put some effort into the reporting, once they know that most intel they will get is what they generate themself, and thus it is important to put down the 20-30 minutes after a flight to do it properly aswell

> 
>     2. In the "CJTF HQ guidance to AOC" phase, we should stress that we need primary as well as secondary/contingency missions so that it's easier for us to account for late signoffs / late signups.

I would not worry to much about that. There is no problem for us to generate / change missions as we see fit to facilitate late signoffs/signups.   The most important thing for CJTF HQ will be to give the priority I think, as it will matter on what happens. So if one do not do anything about the nearby enemy airbases, then the enemy will keep harassing from those airfields. If we dont do anything with the IADS, then it will be hard to conduct strikes into Syria. If we dont support ground forces somewhere, then they enemy will be able to push forward etc.
The rationale of having us as the AOC as the "middlemen" is that we can make sure everything flows nicely from a gameplay perspective to ensure a good experience for everyone.

But we should iron out the tasks/responsibilities in a good way before we start, so we can "recruit" people into these positions, and make sure to give them the proper tools and training to be effective when we start.  So just add in tasks or responsibilities as you see fit here, so we can have it ready
