### ISSUE TITLE
Israeli ground order of battle

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPAR#6]
Documentation to give a understanding of the Israelig ground force (organization and types of units).

**Comment by IAFAssafB** [comment]
(STILL WIP)

### IDF Northern Command
The Israeli Defense Force Northern-Command (IDF-NC)is in charge of defending the international borders with Lebanon and Syria, as well as conducting offensive operations as needed in order to facilitate security. 
During wartime, the Northern-Command may receive reinforcements from the CENTRAL and SOUTHERN commands if conditions dictate it and pending availability of additional assets.
IDF-NC is based on four divisions:

**210th Armored Division**	   
474 Armored Brigade (Merkava)	   
679 Armored Brigade (Merkava)	   
11 Motorized Brigade (M113)	   
810 Motorized Brigade (M113)	   
209 Fire Support Brigade (M270 MLRS, 155mm PALADIN)	   
399 Logistics Brigade (Trucks)	   
	   
**91st Armored Division**	   
188 Armored Brigade (Merkava)	   
434 Armored Brigade (Merkava)	   
484 Motorized Brigade (M113)	   
282 Fire Support Brigade (M270 MLRS)	   
911 Logistics Brigade (Trucks)	   
	   
**319th Armored Division**	   
205 Armored Brigade (Merkava)	   
90 Armored Brigade (Merkava)	   
226 Motorized Brigade (M113)	   
213 Fire Support Brigade (M270 MLRS)	   
3191 Logistics Brigade (Trucks)	   
	   
**98th Paratroopers Division**	   
35 Paratroopers Brigade	   
89 Special Operations Brigade (HMMWV)	   
982 Motorized Brigade (HMMWV)	   
214 Fire Support Brigade (155mm PALADIN, Mortars)	   
981 Logistics Brigade (Trucks)	   
	   
**Air defense**
The Israeli air defense doctrine relies on countering threats using alert fighters as first line of defense and static PATRIOT sites as last line of defense. 

EWR stations:
1) Mt. HERMON
2) Mt. MERON

PATRIOT batteries located at:
1) NORTH of ZEFAT
2) Near HAIFA
